# frontend/render.yaml - Frontend configuration
services:
  - type: web
    name: kairos-frontend
    env: node
    buildCommand: pnpm install --no-frozen-lockfile && pnpm run build
    startCommand: pnpm start
    envVars:
      - key: NODE_VERSION
        value: 20.14.0  # Use a maintained Node.js version
      - key: NEXT_PUBLIC_API_URL
        sync: false
