# backend/render.yaml - Render service configuration
services:
  - type: web
    name: kairos-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api_server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: RECALL_API_KEY
        sync: false
      - key: RECALL_SANDBOX_API_BASE
        value: https://api.competitions.recall.network
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false

